# Configuration for LootRush
# banned-items: Список предметов, которые не должны появляться в игре.
# Вы можете использовать точные названия предметов (например, BEDROCK) или регулярные выражения, начинающиеся с "REGEX:" (например, REGEX:.*_SPAWN_EGG)

# swap-interval-seconds: Интервал между сменами мест в секундах (по умолчанию 300 секунд = 5 минут)
swap-interval-seconds: 300

# scatter-min-coord: Минимальная координата для телепортации (по умолчанию 10000)
scatter-min-coord: 10000

# scatter-max-coord: Максимальная координата для телепортации (по умолчанию 100000)
scatter-max-coord: 100000

banned-items:
  - STRUCTURE_BLOCK
  - JIGSAW
  - COMMAND_BLOCK
  - REPEATING_COMMAND_BLOCK
  - CHAIN_COMMAND_BLOCK
  - BARRIER
  - DEBUG_STICK
  - KNOWLEDGE_BOOK
  - LIGHT
  - BUNDLE
  - BEDROCK
  - BUDDING_AMETHYST
  - COMMAND_BLOCK_MINECART
  - SPAWNER
  - REINFORCED_DEEPSLATE
  - STRUCTURE_VOID
  - END_PORTAL_FRAME
  - END_PORTAL
  - END_GATEWAY
  - NETHER_PORTAL
  - SUSPICIOUS_SAND
  - SUSPICIOUS_GRAVEL
  - ICE
  - PACKED_ICE
  - BLUE_ICE
  - FROSTED_ICE
  - BEE_NEST
  - LARGE_AMETHYST_BUD
  - MEDIUM_AMETHYST_BUD
  - SMALL_AMETHYST_BUD
  - AMETHYST_CLUSTER
  - BROWN_MUSHROOM_BLOCK
  - RED_MUSHROOM_BLOCK
  - MUSHROOM_STEM
  - GRASS_BLOCK
  - MYCELIUM
  - PODZOL
  - SNOW_BLOCK
  - TUBE_CORAL_BLOCK
  - BRAIN_CORAL_BLOCK
  - BUBBLE_CORAL_BLOCK
  - FIRE_CORAL_BLOCK
  - HORN_CORAL_BLOCK
  - DEAD_TUBE_CORAL_BLOCK
  - DEAD_BRAIN_CORAL_BLOCK
  - DEAD_BUBBLE_CORAL_BLOCK
  - DEAD_FIRE_CORAL_BLOCK
  - DEAD_HORN_CORAL_BLOCK
  - REGEX:^MUSIC_DISC.*
  - REGEX:^DISC_FRAGMENT.*
  - REGEX:.*_SPAWN_EGG
  - REGEX:.*_ORE
  - REGEX:^INFESTED_.*
  - REGEX:.*PORTAL.*
  - REGEX:.*COMMAND_BLOCK.*
  - REGEX:.*STRUCTURE.*
  - REGEX:.*BARRIER.*
  - REGEX:.*DEBUG_STICK.*
  - REGEX:.*REINFORCED_DEEPSLATE.*
  - REGEX:.*BUDDING_AMETHYST.*
  - REGEX:.*SPAWNER.*
  - REGEX:.*SUSPICIOUS.*
  - REGEX:.*SHERD.*
  - REGEX:.*CORAL_BLOCK.*
  - REGEX:.*MUSHROOM_BLOCK.*
  - REGEX:.*MUSHROOM_STEM.*
  - REGEX:.*AMETHYST_BUD.*
